# Generated by Django 4.1.3 on 2022-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0002_alter_bmicalculator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmicalculator',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
