# Generated by Django 4.1.3 on 2022-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0003_bmicalculator_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculator',
            name='bmi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bmicalculator',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bmicalculator',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
