# Generated by Django 4.1.3 on 2022-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmicalculator', '0005_remove_bmicalculator_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmicalculator',
            name='user',
        ),
    ]
