# Generated by Django 4.1.3 on 2022-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='poop',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='issue',
            new_name='progress',
        ),
        migrations.AlterField(
            model_name='report',
            name='drink',
            field=models.CharField(choices=[('Tidak Baik', 'Tidak baik'), ('Kurang Baik', 'Kurang baik'), ('Cukup Baik', 'Cukup baik'), ('Sangat Baik', 'Sangat baik')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='eat',
            field=models.CharField(choices=[('Tidak Baik', 'Tidak baik'), ('Kurang Baik', 'Kurang baik'), ('Cukup Baik', 'Cukup baik'), ('Sangat Baik', 'Sangat baik')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='height',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.CharField(max_length=15),
        ),
    ]
