# Generated by Django 4.1 on 2022-10-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_report_poop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='issue',
            new_name='progress',
        ),
    ]
