# Generated by Django 4.1 on 2022-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_issue_report_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='age',
            field=models.CharField(default='0 Tahun', max_length=15),
        ),
    ]
