# Generated by Django 4.1 on 2022-10-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='height',
            field=models.CharField(default='0cm', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.CharField(default='0kg', max_length=15),
        ),
    ]
