# Generated by Django 4.1 on 2022-10-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_height_alter_report_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='progress',
            field=models.TextField(default='-'),
        ),
    ]
