# Generated by Django 4.1 on 2022-10-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='drink',
            field=models.CharField(choices=[('Tidak Baik', 'Tidak baik'), ('Kurang Baik', 'Kurang baik'), ('Cukup Baik', 'Cukup baik'), ('Sangat Baik', 'Sangat baik')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='eat',
            field=models.CharField(choices=[('Tidak Baik', 'Tidak baik'), ('Kurang Baik', 'Kurang baik'), ('Cukup Baik', 'Cukup baik'), ('Sangat Baik', 'Sangat baik')], max_length=15),
        ),
    ]
