# Generated by Django 4.1 on 2022-10-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_drink_alter_report_eat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
