# Generated by Django 4.1 on 2022-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_height_alter_report_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='height',
            field=models.CharField(default='0 cm', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.CharField(default='0 kg', max_length=15),
        ),
    ]
