# Generated by Django 4.1.1 on 2022-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_poop_report_age_rename_issue_report_progress_and_more'),
        ('report', '0009_alter_report_height_alter_report_weight'),
    ]

    operations = [
    ]
