# Generated by Django 4.1.1 on 2022-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('forum', '0004_forum_downvote_forum_upvote'),
    ]

    operations = [
    ]
