# Generated by Django 4.1 on 2022-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating_average',
            field=models.FloatField(default=0),
        ),
    ]
